<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
	</array>
	<key>name</key>
	<string>log</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(^[ 0-9]{5})</string>
			<key>name</key>
			<string>comment.line.number-sign.log</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.actionscript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.log</string>
		</dict>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.haxe.2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.haxe.2</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.haxe.2</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.haxe.2</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.haxe.2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.haxe.2</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.haxe.2</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.haxe.2</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.haxe.2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.haxe.2</string>
		</dict>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(try|catch|throw)\b</string>
					<key>name</key>
					<string>keyword.control.catch-exception.haxe.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+\s*\?\s*\w+\s*:</string>
					<key>name</key>
					<string>keyword.control.ternary-if.haxe.2</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.haxe.flow-control.2</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(if|return|while|for)\b\s*\(</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(return|break|case|continue|default|do|while|for|switch|if|else)\b</string>
					<key>name</key>
					<string>keyword.control.haxe.flow-control.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(==|!=|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;)</string>
					<key>name</key>
					<string>keyword.operator.comparison.haxe.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(=)</string>
					<key>name</key>
					<string>keyword.operator.assignment.haxe.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\.\.\.)</string>
					<key>name</key>
					<string>keyword.control.directive.haxe.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-\-|\+\+)</string>
					<key>name</key>
					<string>keyword.operator.increment-decrement.haxe.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-|\+|\*|\/|%)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.haxe.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(!|&amp;&amp;|\|\|)</string>
					<key>name</key>
					<string>keyword.operator.logical.haxe.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(cast|untyped)\b</string>
					<key>name</key>
					<string>keyword.other.untyped.haxe.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\btrace\b</string>
					<key>name</key>
					<string>keyword.other.trace.haxe.2</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.directive.conditional.haxe.2</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#if\s+([\!\w]+|(\([^\)]*\))))</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(#end|#else|#elseif)\b</string>
					<key>name</key>
					<string>keyword.control.directive.conditional.haxe.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.terminator.haxe.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(this|super)\b</string>
					<key>name</key>
					<string>variable.language.haxe.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(var|new)\b</string>
					<key>name</key>
					<string>keyword.other.variable.haxe.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b__(init|instanceof|string_rec)\b</string>
					<key>name</key>
					<string>support.variable.magic.haxe.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bprototype\b</string>
					<key>name</key>
					<string>support.variable.magic.haxe.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b__(init|name|ename|super|unprotect|constructs|class|enum)__\b</string>
					<key>name</key>
					<string>support.variable.magic.haxe.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Array|ArrayAccess|Bool|Class|Date|DateTools|Dynamic|EReg|Enum|Float|Hash|Int|IntHash|IntIter|Iterable|Iterator|Lambda|List|Math|Null|Reflect|Std|String|StringBuf|StringTools|Type|UInt|ValueType|Void|Xml|XmlType|TBool|TInt|TFloat|TFunction|TObject|TEnum|TClass|TNull|TUnknown)\b</string>
					<key>name</key>
					<string>support.class.haxe</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#storage</string>
				</dict>
			</array>
		</dict>
		<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.class.haxe.2</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.class.haxe.2</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.haxe.2</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
                                (\b(class|enum|interface)|\b(implements|extends))
                                \s+(([a-z]+.)*[_A-Z]\w*)</string>
				</dict>

				
	</array>
	<key>scopeName</key>
	<string>source.log</string>
	<key>uuid</key>
	<string>DA9AA267-9AA7-49C4-B69B-EE9F6BB2BE07</string>
</dict>
</plist>
